<a href="https://colab.research.google.com/github/masvgp/google_colab/blob/master/finite_derivatives.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Backward Difference Method

Import relevant libraries and give them a short name, e.g., rename `numpy` as `np`

In [ ]:
import numpy as np

### Functional Version

Here we will define a Python function `back_diff` that takes any mathematical function `f`, a 1-D array of numbers `x`, and a step-size `h`. The function will return a 1-D array containing the 'backward differences' of `f` applied to `x`. This is similar to computing the derivative $f'$ of the function `f`. For reference, the backward difference formula implemented in ``back_diff`` is $$\frac{f(x) - f(x - h)}{h}.$$

In [ ]:
def back_diff(f, x, h):
  '''
  Implementation of the backward difference formula with step size h.
  f : function
    Vectorized function of a single variable
  x : vector
      a vector of values over which to compute the differences of f at x
  h : number
      Step size in difference formula
  '''

  return (f(x) - f(x - h)) / h

Now we need to define the arguments `f`, `x`, and `h` that will be taken by `back_diff`.

First we define an array of linearly (equally) spaced values, which will eventually be fed to `f`. The numpy function that does this is `numpy.linspace(start, stop, num)`. The arguments are, `start` = starting value, `stop` = ending value, and `num` = number of point to draw from the range `start` to `stop`.

In [ ]:
x = np.linspace(0, 10, 11)
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Now we define the step size, which is really a function of the sample points we drew in the `np.linspace()` function. Specifically, `h = (stop - start)/(num - 1)`. You should be able to explain why we use `num-1` instead of just `num` in the denominator.

In [ ]:
h = (10 - 0)/10
h

1.0

Now we need to define a function `f` to feed to `back_diff`. There are two ways to do this. The 'regular' function way and the anonymous function way. We will show both.

First we start with an anonymous function, which uses Python's `lambda` function. It creates a nameless function. Usually you only do this if you are defining a function with only a single use, which is what we are doing here. The syntax is to call `lambda` with a variable, then a colon and what you want `lambda` to do to the variable. We store the function in `f`. Then when we want to call `f` with an argument, say `x`, we just call it like any other function, `f(x)`.

In [ ]:
f = lambda x: x ** 2

The other way to do this is to create a named function. Like we did with the `back_diff` function.

In [ ]:
def square(x):
  return x ** 2

Finally, we will call `back_diff` and feed it appropriate arguments. We'll do it first with the anonymous function `f`, then with the 'regular' function `square`. You should get the same result out of both function calls.

In [ ]:
back_diff(f, x, h)

array([-1.,  1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

In [ ]:
back_diff(square, x, h)

array([-1.,  1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

### Matrix Version

Now we will create a backward difference matrix `A` that will 'act' on any vector of function values `f(x)` and return the bacward differences.

We start by creating a matrix with ones down the diagonal.

In [ ]:
A = np.eye(10)

Then we add the negative ones on the lower off-diagonal

In [ ]:
for i in range(9):
  A[i + 1, i] = -1

Let's just check that `A` looks the way we think it should.

In [ ]:
A

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -1.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., -1.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., -1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  1.]])

Then we create an array of function values.

In [ ]:
x = square(np.arange(10))

Finally, we compute the backward differences $b$ by taking the dot product $Ax$, that is, we compute $Ax = b$.

In [ ]:
dydx = np.dot(A, x)
dydx

array([ 0.,  1.,  3.,  5.,  7.,  9., 11., 13., 15., 17.])

Now, suppose we wanted to recover `x` from `dydx`. We could use `numpy`'s inverse function from it's linear algebra library like so.

In [ ]:
A_inv = np.linalg.inv(A)
A_inv

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Then we take the dot product $A^{-1}b$ which returns the original $x$.

In [ ]:
x = np.dot(A_inv, dydx)
x

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.])