<a href="https://colab.research.google.com/github/masvgp/google_colab/blob/master/strang_lin_alg_1_2_34_means_and_dot_prods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
v = np.random.randn(3, 1)
u = v/np.linalg.norm(v)
u

array([[-0.62349401],
       [-0.74443463],
       [ 0.23889809]])

In [ ]:
V = np.random.randn(30, 3, 1)

In [ ]:
U = V/np.linalg.norm(V)

In [ ]:
u_dot_U = np.dot(np.transpose(u), U)

array([[[ 0.05951801],
        [-0.06342192],
        [-0.06174345],
        [-0.03686659],
        [ 0.02709753],
        [-0.13907481],
        [ 0.11313056],
        [ 0.1483165 ],
        [-0.0633835 ],
        [ 0.06253375],
        [-0.14603727],
        [ 0.10261034],
        [ 0.04356945],
        [ 0.08448712],
        [-0.1570558 ],
        [ 0.160369  ],
        [ 0.2199208 ],
        [-0.01861362],
        [ 0.0127259 ],
        [-0.11618528],
        [-0.12905485],
        [-0.05767757],
        [-0.10371148],
        [ 0.19220244],
        [ 0.04770791],
        [-0.08920619],
        [ 0.0027949 ],
        [ 0.08731681],
        [ 0.08095016],
        [-0.1448761 ]]])

In [ ]:
u_dot_U = u_dot_U.flatten()

array([ 0.05951801, -0.06342192, -0.06174345, -0.03686659,  0.02709753,
       -0.13907481,  0.11313056,  0.1483165 , -0.0633835 ,  0.06253375,
       -0.14603727,  0.10261034,  0.04356945,  0.08448712, -0.1570558 ,
        0.160369  ,  0.2199208 , -0.01861362,  0.0127259 , -0.11618528,
       -0.12905485, -0.05767757, -0.10371148,  0.19220244,  0.04770791,
       -0.08920619,  0.0027949 ,  0.08731681,  0.08095016, -0.1448761 ])

In [ ]:
np.mean(u_dot_U)

0.003944758737941715

In [ ]:
np.var(u_dot_U)

0.011393554480836756